Issue 2560 - Adição ao suporte de opções de campo para os argumentos dos passos
MPMG-DCC-UFMG/C01 pull request #3061
Opened 2022-05-06 12:29 UTC by matheusfebarbosa

Até o momento, a interface do mecanismo de passos somente suportava a utilização de campos de texto para os argumentos de cada passo.

Este PR adiciona o suporte para a configuração de opções para os argumentos de uma função no mecanismo de passos. Isso pode ser feito através das anotações `@step` utilizadas em cada função, onde um novo argumento `field_options` pode ser utilizado. Ele recebe um dicionário de configuração onde cada argumento da função pode ser configurado com outro dicionário que aceita as seguintes propriedades:

`'field_type'` : Tipo do campo a ser utilizado. Atualmente aceita 'text', 'select', 'number', 'checkbox'.

`'select_options' `: Para ser utilizado em conjunto com o tipo 'select'. Recebe uma lista de strings que será utilizada como opções no campo de seleção.

`'checkbox_label'` : Para ser utilizado em conjunto com o tipo 'checkbox'. Recebe uma string que sera utilizada como label para o checkbox na interface.

`'input_placeholder '` : Para ser utilizado em conjunto com o tipo 'text' e 'number'. Recebe uma string que aparecerá como placeholder para o campo na interface.

Essa nova função do mecanismo de passos é opcional, e caso não seja utilizada pra algum argumento, o seu campo na interface será padronizado para um campo de texto comum.

2022-05-06 12:29 UTC, pep8speaks commented
Hello @matheusfebarbosa! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/step-by-step/step_crawler/functions_file.py`](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py):

> [Line 21:32](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L21): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 21:34](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L21): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 21:80](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 43:31](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L43): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 43:33](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L43): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 44:15](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L44): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 44:31](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L44): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 44:63](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L44): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 44:80](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L44): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 157:43](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L157): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 157:45](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L157): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 158:11](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L158): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 158:27](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L158): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 158:56](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L158): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 158:76](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L158): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 158:80](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L158): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 159:80](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L159): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 276:34](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L276): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 276:36](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L276): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 277:11](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L277): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 277:27](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L277): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 277:56](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L277): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 277:66](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L277): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 277:80](https://github.com/MPMG-DCC-UFMG/C01/blob/c8ce75ba75f5bce14dcc4227ca12cf2832ef41d5/src/step-by-step/step_crawler/functions_file.py#L277): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)

2022-05-09 13:23 UTC, rennancordeiro commented
Olá @matheusfebarbosa, as modificações quebraram os testes. Pode verificar isso por favor? Se é um bug inserido ou se é necessário apenas adaptar o teste para o novo código.

2022-05-23 21:59 UTC, lucasaug approved these changes

2022-05-23 21:59 UTC, lucasaug commented on main/staticfiles/js/step_block.js
>   * @param {Bool} optional_param A boolean that says whether or
Pra manter a padronização, podemos colocar o novo parâmetro `field_options` aqui na documentação também. De toda forma, não é um impeditivo para integrar com a master.

2022-05-23 22:09 UTC, lucasaug requested changes
Acabei encontrando um problema que ia reportar em outra issue, porque não achei que estava associado a essa mudança específica, mas verificando aqui percebi que o erro só existe nessa branch: alguns parâmetros não estão sendo "re-preenchidos" corretamente ao editar. Exemplo: criei uma coleta com a seguinte configuração dinâmica (apenas para fins de teste da interface):

![certo](https://user-images.githubusercontent.com/1329255/169913080-9bd623e4-ee22-40e6-ba17-9a95eec1b2a6.png)

Ao salvar esse coletor e abrí-lo para edição, encontro o campo da seguinte forma:

![err](https://user-images.githubusercontent.com/1329255/169913124-3ed6d9d2-f770-4495-89b3-ca43bfe25a8f.png)

Por algum motivo o valor do último campo é repetido no primeiro. O dicionário gerado parece estar correto, o erro está na hora de refletir o valor dos parâmetros na interface.

2022-06-03 10:21 UTC, matheusfebarbosa commented
Consertado. Também adicionei o comentario de doc na função @lucasaug.

2022-06-03 22:44 UTC, lucasaug approved these changes

2022-06-08 16:48 UTC, louisaturn approved these changes

2022-06-10 13:36 UTC, merged