Issue 959/894 - Resolve bloqueio e HTTP ao iniciar uma coleta
MPMG-DCC-UFMG/C01 pull request #980
Opened 2021-11-28 00:40 UTC by elvesrodrigues

O BUG é estranho mas aparentemente foi resolvido ao refazer as alterações no módulo `distributed_scheduler` em (`spider_manager/src/crawling/distributed_scheduler.py`) com leves modificações.

Resolve #959 e #894.

2021-11-28 00:40 UTC, pep8speaks commented
Hello @elvesrodrigues! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`spider_manager/src/crawling/distributed_scheduler.py`](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py):

> [Line 7:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L7): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 8:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L8): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 12:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 15:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L15): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 16:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L16): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 19:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L19): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 20:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L20): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 21:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L21): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 22:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L22): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 23:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L23): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 26:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L26): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 27:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L27): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 28:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L28): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 29:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L29): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 30:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L30): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 31:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L31): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 34:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L34): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 35:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L35): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 36:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L36): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 39:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L39): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 40:1](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L40): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 48:22](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L48): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 49:22](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L49): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 50:18](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L50): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 51:22](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L51): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 52:23](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L52): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 53:22](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L53): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 56:20](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L56): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 57:23](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/distributed_scheduler.py#L57): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 58:24](https://github.com/MPMG-DCC-UFMG/C01/blob/7d7d5c62663196b5b2573cfa8ffcb02ab1c82ce1/spider_manager/src/crawling/dist [...]

2021-11-28 00:42 UTC, elvesrodrigues commented
@pep8speaks pep8ify

2021-11-28 00:42 UTC, pep8speaks commented
Here you go with [the Pull Request](https://github.com/MPMG-DCC-UFMG/C01/pull/981) ! The fixes are suggested by [autopep8](https://github.com/hhatto/autopep8).

 @elvesrodrigues

2021-11-29 13:50 UTC, rennancordeiro requested changes
Executei a coleta de São Lourenço documentada na issue https://github.com/MPMG-DCC-UFMG/C01/issues/959 e deu tudo certo!

2021-11-29 13:50 UTC, rennancordeiro approved these changes

2021-11-30 02:06 UTC, lucasaug approved these changes
Testei a coleta de Recreio e Betim, e o erro mencionado não ocorre mais.

2021-11-30 02:11 UTC, merged